# PotatoIpDisplay-bukkit 配置文件
# 一款用于显示玩家 IP 归属地的 Minecraft 插件
# 详情：[https://github.com/dmzz-yyhyy/PotatoIpDisplay]

# 请勿修改！
config-version: 3

# 常规设置
options:
  # IPv4 查询模式：
  # - "ip2region"：内置的本地数据库
  # - "pconline"、"ip-api"：在线 API
  mode: "ip2region"

  # IPv6 查询模式：
  # - "disabled"：禁用 IPv6 查询
  # - "zxinc"：使用 https://ip.zxinc.org/ 在线查询
  mode-ipv6: "disabled"

  # 缓存模式：只有模式设置为 ip2region 时生效，用于加速查询。
  # "none": 完全基于文件，不进行缓存。
  # "vindex": 额外占用固定的 512 KB 内存，缓存 VectorIndex 数据。
  # "cbuff": 额外占用文件大小的内存，缓存整个 ip2region.xdb。
  xdb-buffer: "vindex"
  # 开启 bStats 统计
  allow-bstats: true
  # 自定义对于 “未知” 结果返回的值
  custom-unknown-string: "未知"

# 消息设置
messages:
  # 插件内部可用 placeholder 示例（可用于 messages.*.string）：
  # 下列为插件内置变量，部分查询结果可用性取决于数据源。
  # 如果启用了 PAPI 集成，也可以同时使用 PAPI 变量。
  # %msg%        -> 原消息
  # %playerName% -> 玩家名
  # %ipRegion%   -> IP 所属区域
  # %ipCountry%  -> IP 所属国家
  # %ipProvince% -> IP 所属省
  # %ipCity%     -> IP 所属城市
  # %ipISP%      -> IP 所属 ISP
  # %ipFallback% -> 回退变量（省份、国家、城市 中的首个非“未知“值）

  player-chat:
    # 是否接管玩家消息事件。
    # 与其他消息格式化插件冲突。
    enabled: false
    # 消息格式
    string: "§7[§b%ipFallback%§7] §f%playerName% §7>> §f%msg%"

  player-login:
    # 是否在玩家登录后发送一条消息显示 IP 归属地。
    enabled: true
    # 消息格式
    string: "§7[§6PotatoIPDisplay§7] §e您当前IP归属地 §7[§b%ipFallback%§7]"

# Placeholder API 设置
papi:
  # 启用 PAPI 支持。需要安装 Placeholder API。
  enabled: false
  # 可用变量：
  # 请参考 [https://github.com/dmzz-yyhyy/PotatoIpDisplay#placeholder-api]
